#pragma once

#define STRINGIGY(macro) #macro
#define STRINGIGY2(macro) STRINGIGY(macro)

#define VIDEOWITHALPHA_VERSION_MAJOR 1
#define VIDEOWITHALPHA_VERSION_MINOR 1
#define VIDEOWITHALPHA_VERSION_BUGFIX 0

#define VIDEOWITHALPHA_VERSION_STR \
    STRINGIGY2(VIDEOWITHALPHA_VERSION_MAJOR) "." \
    STRINGIGY2(VIDEOWITHALPHA_VERSION_MINOR) "-" \
    STRINGIGY2(VIDEOWITHALPHA_VERSION_BUGFIX)

